// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd0_EXSJMKHY0KVi6ibnbtFLunPjlv47g',
    appId: '1:769895385898:web:f286a4ddf1786ac3f8ac53',
    messagingSenderId: '769895385898',
    projectId: 'anamak-8eaeb',
    authDomain: 'anamak-8eaeb.firebaseapp.com',
    storageBucket: 'anamak-8eaeb.appspot.com',
    measurementId: 'G-4NF0JR5L2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzTiVeq1sor-lV5P1yWnENMB98x4eUY8M',
    appId: '1:769895385898:android:24fd2381e0ca3e8cf8ac53',
    messagingSenderId: '769895385898',
    projectId: 'anamak-8eaeb',
    storageBucket: 'anamak-8eaeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoMpHYTVHuC5i2FxrhRf8urfkUJ0_sN6U',
    appId: '1:769895385898:ios:9ef942b6a9110f44f8ac53',
    messagingSenderId: '769895385898',
    projectId: 'anamak-8eaeb',
    storageBucket: 'anamak-8eaeb.appspot.com',
    iosClientId: '769895385898-7amaes311uslmgv8oj5kd3utljbc34ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.crazyAnamak.RunnerTests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoMpHYTVHuC5i2FxrhRf8urfkUJ0_sN6U',
    appId: '1:769895385898:ios:9ef942b6a9110f44f8ac53',
    messagingSenderId: '769895385898',
    projectId: 'anamak-8eaeb',
    storageBucket: 'anamak-8eaeb.appspot.com',
    iosClientId: '769895385898-7amaes311uslmgv8oj5kd3utljbc34ab.apps.googleusercontent.com',
    iosBundleId: 'com.example.crazyAnamak.RunnerTests',
  );
}
